version: '3'
services:
  postgres:
      image: postgres:9.6
      container_name: pg_airflow_databook
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      ports:
          - 5432:5432
      networks:
        - databooknet
  webserver:
      image: puckel/docker-airflow:1.8.0
      container_name: airflow_databook
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      volumes:
          - ./dags:/usr/local/airflow/dags
          - ./docker/airflow/requirements.txt:/requirements.txt
      ports:
          - 8080:8080
      command: webserver
      networks:
        - databooknet
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
      container_name: elasticsearch_databook
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.ml.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - databooknet
  neo4j:
      image: neo4j:3.3.0
      container_name: neo4j_databook
      environment:
        - NEO4J_AUTH=neo4j/j4oen
      depends_on:
        - elasticsearch
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      volumes:
          - ./docker/neo4j/conf:/conf
          - ./docker/neo4j/data:/data
          - ./docker/neo4j/import:/import
          - ./docker/neo4j/plugins:/plugins
      networks:
        - databooknet
  databook:
      image: gtoonstra/databook:0.1.0
      container_name: databook
      depends_on:
        - elasticsearch
        - neo4j
      ports:
        - 5000:5000
      networks:
        - databooknet

networks:
  databooknet:
